---
title: "An R Markdown template for English report"
subtitle: "with asa article format"
author: "Qiushi"
date: "`r Sys.Date()`"
bibliography: references.bib
biblio-style: "apalike"
link-citations: true
links-as-notes: yes
colorlinks: yes
output: 
  bookdown::pdf_book:
    base_format: rticles::asa_article
    latex_engine: xelatex
    toc: true
    number_sections: true
blinded: 0
authors: 
- name: Qiushi Yan
  thanks: The authors gratefully acknowledge ...
  affiliation: Unversity 
keywords:
- Machine Learning
- Statistics
abstract: |
  R is a free software environment for statistical computing and graphics. It compiles and runs on a wide variety of UNIX platforms, Windows and MacOS. To download R, please choose your preferred CRAN mirror.
  If you have questions about R like how to download and install the software, or what the license terms are, please read our answers to frequently asked questions before you send an email.
lof: true
lot: true
geometry: margin=1.18in
fontsize: 12pt
linestretch: 1.5
#nocite: '@*'
---

```{r, include = FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE, 
                      collapse = TRUE,
                      comment = "#>")
```


```{r, include = FALSE}
knitr::opts_chunk$set(message = FALSE)
```


# Chapter 1

theorem and math environments \@ref(thm:pyth)

```{theorem, pyth, name="Pythagorean theorem"}
For a right triangle, if $c$ denotes the length of the hypotenuse
and $a$ and $b$ denote the lengths of the other two sides, we have

$$a^2 + b^2 = c^2$$
```

# Chapter 2

cross referencing figures \@ref(fig:diamond-plot)
```{r diamond-plot, fig.cap = "this is a figure", fig.height = 4}
library(dplyr)
library(ggplot2)

diamonds %>% 
  slice_sample(n = 500) %>%
  ggplot() + 
  geom_point(aes(carat, price, color = cut)) + 
  theme_minimal()
```



cross referencing tables \@ref(tab:iris)

```{r iris, echo = FALSE}
knitr::kable(head(iris), caption = "my table")
```


